FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock* ./

ENV UV_PROJECT_ENVIRONMENT=/opt/venv

RUN uv sync --frozen --no-dev --no-install-project

COPY . .

ENV PYTHONPATH=/app
ENV PATH="/opt/venv/bin:$PATH"

CMD ["taskiq", "worker", "app.background.taskiq.taskiq:broker", "--tasks-pattern", "app/background/taskiq/tasks/*.py"]