"""Made organization point to users and fields of Organization nullable.

Revision ID: 5d36ba577387
Revises: 45b93ed02ddf
Create Date: 2026-04-24 05:36:13.080960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d36ba577387'
down_revision: Union[str, Sequence[str], None] = '45b93ed02ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('account_id', sa.Integer(), nullable=True))
    op.alter_column('organizations', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('organizations', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('organizations_name_key'), 'organizations', type_='unique')
    op.create_foreign_key(None, 'organizations', 'users', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('organizations', 'name')
    op.add_column('users', sa.Column('is_organization', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_organization')
    op.add_column('organizations', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_unique_constraint(op.f('organizations_name_key'), 'organizations', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('organizations', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('organizations', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('organizations', 'account_id')
    # ### end Alembic commands ###
